# Generated by Django 5.1.7 on 2025-03-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearist', '0003_category_remove_products_uploaded_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='material',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
