# Generated by Django 5.1.7 on 2025-04-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wearist', '0004_products_description_alter_products_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
